// This file is @generated by prost-build.
/// `build/scene.grav` (per-scene embedded prefab defs + build instances).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDat {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(uint32, tag = "2")]
    pub units_per_meter: u32,
    #[prost(message, repeated, tag = "3")]
    pub defs: ::prost::alloc::vec::Vec<SceneDatObjectDef>,
    #[prost(message, repeated, tag = "4")]
    pub instances: ::prost::alloc::vec::Vec<SceneDatObjectInstance>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Float32Dat {
    #[prost(float, tag = "1")]
    pub value: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ColorDat {
    #[prost(fixed32, tag = "1")]
    pub rgba: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EmptyDat {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDatObjectInstance {
    #[prost(message, optional, tag = "1")]
    pub instance_id: ::core::option::Option<super::super::common::v1::Uuid128>,
    #[prost(message, optional, tag = "2")]
    pub base_object_id: ::core::option::Option<super::super::common::v1::Uuid128>,
    #[prost(int32, tag = "3")]
    pub x_units: i32,
    #[prost(int32, tag = "4")]
    pub y_units: i32,
    #[prost(int32, tag = "5")]
    pub z_units: i32,
    #[prost(float, tag = "6")]
    pub rot_x: f32,
    #[prost(float, tag = "7")]
    pub rot_y: f32,
    #[prost(float, tag = "8")]
    pub rot_z: f32,
    #[prost(float, tag = "9")]
    pub rot_w: f32,
    #[prost(message, optional, tag = "10")]
    pub tint: ::core::option::Option<ColorDat>,
    #[prost(message, optional, tag = "11")]
    pub scale_x: ::core::option::Option<Float32Dat>,
    #[prost(message, optional, tag = "12")]
    pub scale_y: ::core::option::Option<Float32Dat>,
    #[prost(message, optional, tag = "13")]
    pub scale_z: ::core::option::Option<Float32Dat>,
    #[prost(message, repeated, tag = "14")]
    pub forms: ::prost::alloc::vec::Vec<super::super::common::v1::Uuid128>,
    #[prost(uint32, tag = "15")]
    pub active_form: u32,
    /// Note: tag gap 16..18 reserved for removed fields.
    #[prost(bool, tag = "19")]
    pub is_protagonist: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDatObjectDef {
    #[prost(message, optional, tag = "1")]
    pub object_id: ::core::option::Option<super::super::common::v1::Uuid128>,
    #[prost(string, tag = "2")]
    pub label: ::prost::alloc::string::String,
    #[prost(float, tag = "3")]
    pub size_x: f32,
    #[prost(float, tag = "4")]
    pub size_y: f32,
    #[prost(float, tag = "5")]
    pub size_z: f32,
    #[prost(message, optional, tag = "6")]
    pub collider: ::core::option::Option<SceneDatCollider>,
    #[prost(message, optional, tag = "7")]
    pub interaction: ::core::option::Option<SceneDatInteraction>,
    #[prost(message, repeated, tag = "8")]
    pub parts: ::prost::alloc::vec::Vec<SceneDatPartDef>,
    #[prost(message, optional, tag = "9")]
    pub minimap_color: ::core::option::Option<ColorDat>,
    #[prost(message, optional, tag = "10")]
    pub health_bar_offset_y: ::core::option::Option<Float32Dat>,
    #[prost(message, repeated, tag = "11")]
    pub anchors: ::prost::alloc::vec::Vec<SceneDatAnchorDef>,
    #[prost(message, optional, tag = "12")]
    pub mobility: ::core::option::Option<SceneDatMobility>,
    #[prost(message, optional, tag = "13")]
    pub projectile: ::core::option::Option<SceneDatProjectile>,
    #[prost(message, optional, tag = "14")]
    pub attack: ::core::option::Option<SceneDatUnitAttack>,
    #[prost(message, optional, tag = "15")]
    pub aim: ::core::option::Option<SceneDatAimProfile>,
    #[prost(message, optional, tag = "16")]
    pub ground_origin_y: ::core::option::Option<Float32Dat>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDatAimProfile {
    #[prost(message, optional, tag = "1")]
    pub max_yaw_delta_degrees: ::core::option::Option<Float32Dat>,
    #[prost(message, repeated, tag = "2")]
    pub components: ::prost::alloc::vec::Vec<super::super::common::v1::Uuid128>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatMobility {
    #[prost(enumeration = "SceneDatMobilityMode", tag = "1")]
    pub mode: i32,
    #[prost(float, tag = "2")]
    pub max_speed: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatProjectile {
    #[prost(enumeration = "SceneDatProjectileObstacleRule", tag = "1")]
    pub obstacle_rule: i32,
    #[prost(float, tag = "2")]
    pub speed: f32,
    #[prost(float, tag = "3")]
    pub ttl_secs: f32,
    #[prost(int32, tag = "4")]
    pub damage: i32,
    #[prost(bool, tag = "5")]
    pub spawn_energy_impact: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDatUnitAttack {
    #[prost(enumeration = "SceneDatUnitAttackKind", tag = "1")]
    pub kind: i32,
    #[prost(float, tag = "2")]
    pub cooldown_secs: f32,
    #[prost(int32, tag = "3")]
    pub damage: i32,
    #[prost(float, tag = "4")]
    pub anim_window_secs: f32,
    #[prost(message, optional, tag = "5")]
    pub melee: ::core::option::Option<SceneDatMeleeAttack>,
    #[prost(message, optional, tag = "6")]
    pub ranged: ::core::option::Option<SceneDatRangedAttack>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatMeleeAttack {
    #[prost(float, tag = "1")]
    pub range: f32,
    #[prost(float, tag = "2")]
    pub radius: f32,
    #[prost(float, tag = "3")]
    pub arc_degrees: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDatRangedAttack {
    #[prost(message, optional, tag = "1")]
    pub projectile_prefab: ::core::option::Option<super::super::common::v1::Uuid128>,
    #[prost(message, optional, tag = "2")]
    pub muzzle: ::core::option::Option<SceneDatAnchorRef>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDatAnchorRef {
    #[prost(message, optional, tag = "1")]
    pub object_id: ::core::option::Option<super::super::common::v1::Uuid128>,
    #[prost(string, tag = "2")]
    pub anchor: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDatAnchorDef {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub transform: ::core::option::Option<SceneDatTransform>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatCollider {
    #[prost(oneof = "scene_dat_collider::Kind", tags = "1, 2, 3")]
    pub kind: ::core::option::Option<scene_dat_collider::Kind>,
}
/// Nested message and enum types in `SceneDatCollider`.
pub mod scene_dat_collider {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        None(super::EmptyDat),
        #[prost(message, tag = "2")]
        CircleXz(super::SceneDatCircleXz),
        #[prost(message, tag = "3")]
        AabbXz(super::SceneDatAabbXz),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatCircleXz {
    #[prost(float, tag = "1")]
    pub radius: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatAabbXz {
    #[prost(float, tag = "1")]
    pub half_x: f32,
    #[prost(float, tag = "2")]
    pub half_z: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatInteraction {
    #[prost(bool, tag = "1")]
    pub blocks_bullets: bool,
    #[prost(bool, tag = "2")]
    pub blocks_laser: bool,
    #[prost(message, optional, tag = "3")]
    pub movement_block: ::core::option::Option<SceneDatMovementBlock>,
    #[prost(bool, tag = "4")]
    pub supports_standing: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatMovementBlock {
    #[prost(oneof = "scene_dat_movement_block::Kind", tags = "1, 2")]
    pub kind: ::core::option::Option<scene_dat_movement_block::Kind>,
}
/// Nested message and enum types in `SceneDatMovementBlock`.
pub mod scene_dat_movement_block {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Always(super::EmptyDat),
        #[prost(message, tag = "2")]
        UpperBodyFraction(super::Float32Dat),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDatPartDef {
    #[prost(message, optional, tag = "1")]
    pub part_id: ::core::option::Option<super::super::common::v1::Uuid128>,
    #[prost(message, optional, tag = "2")]
    pub transform: ::core::option::Option<SceneDatTransform>,
    #[prost(message, optional, tag = "6")]
    pub attachment: ::core::option::Option<SceneDatAttachment>,
    #[prost(message, repeated, tag = "7")]
    pub animations: ::prost::alloc::vec::Vec<SceneDatPartAnimationSlot>,
    #[prost(message, optional, tag = "8")]
    pub fallback_basis: ::core::option::Option<SceneDatTransform>,
    #[prost(oneof = "scene_dat_part_def::Kind", tags = "3, 4, 5")]
    pub kind: ::core::option::Option<scene_dat_part_def::Kind>,
}
/// Nested message and enum types in `SceneDatPartDef`.
pub mod scene_dat_part_def {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "3")]
        ObjectRef(super::super::super::common::v1::Uuid128),
        #[prost(message, tag = "4")]
        Primitive(super::SceneDatPrimitive),
        #[prost(string, tag = "5")]
        Model(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDatAttachment {
    #[prost(string, tag = "1")]
    pub parent_anchor: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub child_anchor: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDatPartAnimationSlot {
    #[prost(string, tag = "1")]
    pub channel: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub animation: ::core::option::Option<SceneDatPartAnimation>,
    #[prost(enumeration = "SceneDatPartAnimationFamily", tag = "3")]
    pub family: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDatPartAnimation {
    #[prost(enumeration = "SceneDatPartAnimationDriver", tag = "3")]
    pub driver: i32,
    #[prost(float, tag = "4")]
    pub speed_scale: f32,
    #[prost(float, tag = "5")]
    pub time_offset_units: f32,
    #[prost(message, optional, tag = "8")]
    pub basis: ::core::option::Option<SceneDatTransform>,
    /// NOTE: keep tags disjoint from the non-oneof fields below (driver/speed/time_offset/basis).
    #[prost(oneof = "scene_dat_part_animation::Kind", tags = "1, 2, 6, 7")]
    pub kind: ::core::option::Option<scene_dat_part_animation::Kind>,
}
/// Nested message and enum types in `SceneDatPartAnimation`.
pub mod scene_dat_part_animation {
    /// NOTE: keep tags disjoint from the non-oneof fields below (driver/speed/time_offset/basis).
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Loop(super::SceneDatPartAnimationLoop),
        #[prost(message, tag = "2")]
        Spin(super::SceneDatPartAnimationSpin),
        #[prost(message, tag = "6")]
        Once(super::SceneDatPartAnimationLoop),
        #[prost(message, tag = "7")]
        PingPong(super::SceneDatPartAnimationLoop),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDatPartAnimationLoop {
    #[prost(float, tag = "1")]
    pub duration_secs: f32,
    #[prost(message, repeated, tag = "2")]
    pub keyframes: ::prost::alloc::vec::Vec<SceneDatPartAnimationKeyframe>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatPartAnimationSpin {
    #[prost(float, tag = "1")]
    pub axis_x: f32,
    #[prost(float, tag = "2")]
    pub axis_y: f32,
    #[prost(float, tag = "3")]
    pub axis_z: f32,
    #[prost(float, tag = "4")]
    pub radians_per_unit: f32,
    #[prost(enumeration = "SceneDatPartAnimationSpinAxisSpace", tag = "5")]
    pub axis_space: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatPartAnimationKeyframe {
    #[prost(float, tag = "1")]
    pub time_secs: f32,
    #[prost(message, optional, tag = "2")]
    pub delta: ::core::option::Option<SceneDatTransform>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatTransform {
    #[prost(float, tag = "1")]
    pub tx: f32,
    #[prost(float, tag = "2")]
    pub ty: f32,
    #[prost(float, tag = "3")]
    pub tz: f32,
    #[prost(float, tag = "4")]
    pub rx: f32,
    #[prost(float, tag = "5")]
    pub ry: f32,
    #[prost(float, tag = "6")]
    pub rz: f32,
    #[prost(float, tag = "7")]
    pub rw: f32,
    #[prost(float, tag = "8")]
    pub sx: f32,
    #[prost(float, tag = "9")]
    pub sy: f32,
    #[prost(float, tag = "10")]
    pub sz: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatPrimitive {
    #[prost(oneof = "scene_dat_primitive::Kind", tags = "1, 2")]
    pub kind: ::core::option::Option<scene_dat_primitive::Kind>,
}
/// Nested message and enum types in `SceneDatPrimitive`.
pub mod scene_dat_primitive {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        MeshRef(super::SceneDatPrimitiveMeshRef),
        #[prost(message, tag = "2")]
        Solid(super::SceneDatPrimitiveSolid),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatPrimitiveMeshRef {
    #[prost(enumeration = "SceneDatMeshKey", tag = "1")]
    pub mesh: i32,
    #[prost(message, optional, tag = "2")]
    pub material: ::core::option::Option<SceneDatMaterialKey>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatPrimitiveSolid {
    #[prost(enumeration = "SceneDatMeshKey", tag = "1")]
    pub mesh: i32,
    #[prost(message, optional, tag = "2")]
    pub params: ::core::option::Option<SceneDatPrimitiveParams>,
    #[prost(message, optional, tag = "3")]
    pub color: ::core::option::Option<ColorDat>,
    #[prost(bool, tag = "4")]
    pub unlit: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatMaterialKey {
    #[prost(oneof = "scene_dat_material_key::Kind", tags = "1, 2, 3, 4, 5, 6")]
    pub kind: ::core::option::Option<scene_dat_material_key::Kind>,
}
/// Nested message and enum types in `SceneDatMaterialKey`.
pub mod scene_dat_material_key {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        BuildBlock(super::SceneDatBuildBlock),
        #[prost(message, tag = "2")]
        FenceStake(super::EmptyDat),
        #[prost(message, tag = "3")]
        FenceStick(super::EmptyDat),
        #[prost(message, tag = "4")]
        TreeTrunk(super::SceneDatTreeVariant),
        #[prost(message, tag = "5")]
        TreeMain(super::SceneDatTreeVariant),
        #[prost(message, tag = "6")]
        TreeCrown(super::SceneDatTreeVariant),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatBuildBlock {
    #[prost(uint32, tag = "1")]
    pub index: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatTreeVariant {
    #[prost(uint32, tag = "1")]
    pub variant: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatPrimitiveParams {
    #[prost(oneof = "scene_dat_primitive_params::Kind", tags = "1, 2, 3")]
    pub kind: ::core::option::Option<scene_dat_primitive_params::Kind>,
}
/// Nested message and enum types in `SceneDatPrimitiveParams`.
pub mod scene_dat_primitive_params {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Capsule(super::SceneDatCapsuleParams),
        #[prost(message, tag = "2")]
        ConicalFrustum(super::SceneDatConicalFrustumParams),
        #[prost(message, tag = "3")]
        Torus(super::SceneDatTorusParams),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatCapsuleParams {
    #[prost(float, tag = "1")]
    pub radius: f32,
    #[prost(float, tag = "2")]
    pub half_length: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatConicalFrustumParams {
    #[prost(float, tag = "1")]
    pub radius_top: f32,
    #[prost(float, tag = "2")]
    pub radius_bottom: f32,
    #[prost(float, tag = "3")]
    pub height: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SceneDatTorusParams {
    #[prost(float, tag = "1")]
    pub minor_radius: f32,
    #[prost(float, tag = "2")]
    pub major_radius: f32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SceneDatMobilityMode {
    Ground = 0,
    Air = 1,
}
impl SceneDatMobilityMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Ground => "GROUND",
            Self::Air => "AIR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GROUND" => Some(Self::Ground),
            "AIR" => Some(Self::Air),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SceneDatProjectileObstacleRule {
    BulletsBlockers = 0,
    LaserBlockers = 1,
}
impl SceneDatProjectileObstacleRule {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::BulletsBlockers => "BULLETS_BLOCKERS",
            Self::LaserBlockers => "LASER_BLOCKERS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BULLETS_BLOCKERS" => Some(Self::BulletsBlockers),
            "LASER_BLOCKERS" => Some(Self::LaserBlockers),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SceneDatUnitAttackKind {
    Unknown = 0,
    Melee = 1,
    RangedProjectile = 2,
}
impl SceneDatUnitAttackKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Melee => "MELEE",
            Self::RangedProjectile => "RANGED_PROJECTILE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "MELEE" => Some(Self::Melee),
            "RANGED_PROJECTILE" => Some(Self::RangedProjectile),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SceneDatPartAnimationFamily {
    Base = 0,
    Overlay = 1,
}
impl SceneDatPartAnimationFamily {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Base => "BASE",
            Self::Overlay => "OVERLAY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BASE" => Some(Self::Base),
            "OVERLAY" => Some(Self::Overlay),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SceneDatPartAnimationDriver {
    Always = 0,
    MovePhase = 1,
    MoveDistance = 2,
    AttackTime = 3,
    ActionTime = 4,
}
impl SceneDatPartAnimationDriver {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Always => "ALWAYS",
            Self::MovePhase => "MOVE_PHASE",
            Self::MoveDistance => "MOVE_DISTANCE",
            Self::AttackTime => "ATTACK_TIME",
            Self::ActionTime => "ACTION_TIME",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ALWAYS" => Some(Self::Always),
            "MOVE_PHASE" => Some(Self::MovePhase),
            "MOVE_DISTANCE" => Some(Self::MoveDistance),
            "ATTACK_TIME" => Some(Self::AttackTime),
            "ACTION_TIME" => Some(Self::ActionTime),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SceneDatPartAnimationSpinAxisSpace {
    Join = 0,
    ChildLocal = 1,
}
impl SceneDatPartAnimationSpinAxisSpace {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Join => "JOIN",
            Self::ChildLocal => "CHILD_LOCAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "JOIN" => Some(Self::Join),
            "CHILD_LOCAL" => Some(Self::ChildLocal),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SceneDatMeshKey {
    UnitCube = 0,
    UnitCylinder = 1,
    UnitCone = 2,
    UnitSphere = 3,
    UnitPlane = 4,
    UnitCapsule = 5,
    UnitConicalFrustum = 6,
    UnitTorus = 7,
    UnitTriangle = 8,
    UnitTetrahedron = 9,
    TreeTrunk = 10,
    TreeCone = 11,
}
impl SceneDatMeshKey {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnitCube => "UNIT_CUBE",
            Self::UnitCylinder => "UNIT_CYLINDER",
            Self::UnitCone => "UNIT_CONE",
            Self::UnitSphere => "UNIT_SPHERE",
            Self::UnitPlane => "UNIT_PLANE",
            Self::UnitCapsule => "UNIT_CAPSULE",
            Self::UnitConicalFrustum => "UNIT_CONICAL_FRUSTUM",
            Self::UnitTorus => "UNIT_TORUS",
            Self::UnitTriangle => "UNIT_TRIANGLE",
            Self::UnitTetrahedron => "UNIT_TETRAHEDRON",
            Self::TreeTrunk => "TREE_TRUNK",
            Self::TreeCone => "TREE_CONE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNIT_CUBE" => Some(Self::UnitCube),
            "UNIT_CYLINDER" => Some(Self::UnitCylinder),
            "UNIT_CONE" => Some(Self::UnitCone),
            "UNIT_SPHERE" => Some(Self::UnitSphere),
            "UNIT_PLANE" => Some(Self::UnitPlane),
            "UNIT_CAPSULE" => Some(Self::UnitCapsule),
            "UNIT_CONICAL_FRUSTUM" => Some(Self::UnitConicalFrustum),
            "UNIT_TORUS" => Some(Self::UnitTorus),
            "UNIT_TRIANGLE" => Some(Self::UnitTriangle),
            "UNIT_TETRAHEDRON" => Some(Self::UnitTetrahedron),
            "TREE_TRUNK" => Some(Self::TreeTrunk),
            "TREE_CONE" => Some(Self::TreeCone),
            _ => None,
        }
    }
}
