// This file is @generated by prost-build.
/// A UUID stored as two u64 words (big-endian when reassembled into u128).
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Uuid128 {
    #[prost(fixed64, tag = "1")]
    pub hi: u64,
    #[prost(fixed64, tag = "2")]
    pub lo: u64,
}
