// This file is @generated by prost-build.
/// `build/terrain.grav` (per-scene terrain selection + embedded terrain def).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneTerrainDat {
    /// v1: terrain_id only
    /// v2: terrain_id + embedded terrain_def
    #[prost(uint32, tag = "1")]
    pub format_version: u32,
    /// Optional: the realm terrain package id. Omitted for Default Terrain.
    #[prost(message, optional, tag = "2")]
    pub terrain_id: ::core::option::Option<super::super::common::v1::Uuid128>,
    /// Optional: embedded terrain definition so the scene can render without the realm package.
    #[prost(message, optional, tag = "3")]
    pub terrain_def: ::core::option::Option<TerrainDefV1>,
}
/// Canonical terrain definition (mirrors `terrain_def_v1.json` / `FloorDefV1`).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TerrainDefV1 {
    #[prost(uint32, tag = "1")]
    pub format_version: u32,
    #[prost(string, optional, tag = "2")]
    pub label: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "3")]
    pub mesh: ::core::option::Option<TerrainMeshV1>,
    #[prost(message, optional, tag = "4")]
    pub material: ::core::option::Option<TerrainMaterialV1>,
    #[prost(message, optional, tag = "5")]
    pub coloring: ::core::option::Option<TerrainColoringV1>,
    #[prost(message, optional, tag = "6")]
    pub relief: ::core::option::Option<TerrainReliefV1>,
    #[prost(message, optional, tag = "7")]
    pub animation: ::core::option::Option<TerrainAnimationV1>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TerrainMeshV1 {
    #[prost(enumeration = "TerrainMeshKind", tag = "1")]
    pub kind: i32,
    #[prost(float, tag = "2")]
    pub size_x_m: f32,
    #[prost(float, tag = "3")]
    pub size_z_m: f32,
    #[prost(uint32, tag = "4")]
    pub subdiv_x: u32,
    #[prost(uint32, tag = "5")]
    pub subdiv_z: u32,
    #[prost(float, tag = "6")]
    pub thickness_m: f32,
    #[prost(float, tag = "7")]
    pub uv_tiling_x: f32,
    #[prost(float, tag = "8")]
    pub uv_tiling_z: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TerrainMaterialV1 {
    #[prost(float, tag = "1")]
    pub base_color_r: f32,
    #[prost(float, tag = "2")]
    pub base_color_g: f32,
    #[prost(float, tag = "3")]
    pub base_color_b: f32,
    #[prost(float, tag = "4")]
    pub base_color_a: f32,
    #[prost(float, tag = "5")]
    pub metallic: f32,
    #[prost(float, tag = "6")]
    pub roughness: f32,
    #[prost(bool, tag = "7")]
    pub unlit: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TerrainNoiseV1 {
    #[prost(uint32, tag = "1")]
    pub seed: u32,
    #[prost(float, tag = "2")]
    pub frequency: f32,
    #[prost(uint32, tag = "3")]
    pub octaves: u32,
    #[prost(float, tag = "4")]
    pub lacunarity: f32,
    #[prost(float, tag = "5")]
    pub gain: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TerrainColorRgba {
    #[prost(float, tag = "1")]
    pub r: f32,
    #[prost(float, tag = "2")]
    pub g: f32,
    #[prost(float, tag = "3")]
    pub b: f32,
    #[prost(float, tag = "4")]
    pub a: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TerrainColoringV1 {
    #[prost(enumeration = "TerrainColoringMode", tag = "1")]
    pub mode: i32,
    #[prost(message, repeated, tag = "2")]
    pub palette: ::prost::alloc::vec::Vec<TerrainColorRgba>,
    #[prost(float, tag = "3")]
    pub scale_x: f32,
    #[prost(float, tag = "4")]
    pub scale_z: f32,
    #[prost(float, tag = "5")]
    pub angle_deg: f32,
    #[prost(message, optional, tag = "6")]
    pub noise: ::core::option::Option<TerrainNoiseV1>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TerrainReliefV1 {
    #[prost(enumeration = "TerrainReliefMode", tag = "1")]
    pub mode: i32,
    #[prost(float, tag = "2")]
    pub amplitude: f32,
    #[prost(message, optional, tag = "3")]
    pub noise: ::core::option::Option<TerrainNoiseV1>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TerrainWaveV1 {
    #[prost(float, tag = "1")]
    pub amplitude: f32,
    #[prost(float, tag = "2")]
    pub wavelength: f32,
    #[prost(float, tag = "3")]
    pub direction_x: f32,
    #[prost(float, tag = "4")]
    pub direction_z: f32,
    #[prost(float, tag = "5")]
    pub speed: f32,
    #[prost(float, tag = "6")]
    pub phase: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TerrainAnimationV1 {
    #[prost(enumeration = "TerrainAnimationMode", tag = "1")]
    pub mode: i32,
    #[prost(message, repeated, tag = "2")]
    pub waves: ::prost::alloc::vec::Vec<TerrainWaveV1>,
    #[prost(float, tag = "3")]
    pub normal_strength: f32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TerrainMeshKind {
    Grid = 0,
}
impl TerrainMeshKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Grid => "TERRAIN_MESH_KIND_GRID",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TERRAIN_MESH_KIND_GRID" => Some(Self::Grid),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TerrainColoringMode {
    Solid = 0,
    Checker = 1,
    Stripes = 2,
    Gradient = 3,
    Noise = 4,
}
impl TerrainColoringMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Solid => "TERRAIN_COLORING_MODE_SOLID",
            Self::Checker => "TERRAIN_COLORING_MODE_CHECKER",
            Self::Stripes => "TERRAIN_COLORING_MODE_STRIPES",
            Self::Gradient => "TERRAIN_COLORING_MODE_GRADIENT",
            Self::Noise => "TERRAIN_COLORING_MODE_NOISE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TERRAIN_COLORING_MODE_SOLID" => Some(Self::Solid),
            "TERRAIN_COLORING_MODE_CHECKER" => Some(Self::Checker),
            "TERRAIN_COLORING_MODE_STRIPES" => Some(Self::Stripes),
            "TERRAIN_COLORING_MODE_GRADIENT" => Some(Self::Gradient),
            "TERRAIN_COLORING_MODE_NOISE" => Some(Self::Noise),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TerrainReliefMode {
    None = 0,
    Noise = 1,
}
impl TerrainReliefMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "TERRAIN_RELIEF_MODE_NONE",
            Self::Noise => "TERRAIN_RELIEF_MODE_NOISE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TERRAIN_RELIEF_MODE_NONE" => Some(Self::None),
            "TERRAIN_RELIEF_MODE_NOISE" => Some(Self::Noise),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TerrainAnimationMode {
    None = 0,
    Cpu = 1,
    Gpu = 2,
}
impl TerrainAnimationMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "TERRAIN_ANIMATION_MODE_NONE",
            Self::Cpu => "TERRAIN_ANIMATION_MODE_CPU",
            Self::Gpu => "TERRAIN_ANIMATION_MODE_GPU",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TERRAIN_ANIMATION_MODE_NONE" => Some(Self::None),
            "TERRAIN_ANIMATION_MODE_CPU" => Some(Self::Cpu),
            "TERRAIN_ANIMATION_MODE_GPU" => Some(Self::Gpu),
            _ => None,
        }
    }
}
