use bevy::prelude::*;
use bevy::ui::UiSystems;

use crate::build;
use crate::combat;
use crate::common;
use crate::console;
use crate::effects;
use crate::enemies;
use crate::locomotion;
use crate::physics;
use crate::player;
use crate::rts;
use crate::scene_store;
use crate::setup;
use crate::types::{AutoSpawnEnemies, BuildScene, GameMode};
use crate::unit_health;

pub(crate) struct RenderedStartupPlugin;

impl Plugin for RenderedStartupPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(Startup, setup::setup_rendered);
        app.add_systems(
            Startup,
            crate::workspace_ui::setup_workspace_ui.after(setup::setup_rendered),
        );
        app.add_systems(
            Startup,
            crate::scene_authoring_ui::setup_scene_authoring_ui.after(setup::setup_rendered),
        );
        app.add_systems(
            Startup,
            crate::model_library_ui::setup_model_library_ui.after(setup::setup_rendered),
        );
        app.add_systems(
            Startup,
            crate::motion_ui::setup_motion_algorithm_ui.after(setup::setup_rendered),
        );
        app.add_systems(
            Startup,
            crate::action_log_ui::setup_action_log_ui.after(setup::setup_rendered),
        );
        app.add_systems(
            Startup,
            crate::realm::realm_startup_init.after(setup::setup_rendered),
        );
        app.add_systems(
            Startup,
            scene_store::load_scene_dat
                .after(crate::realm::realm_startup_init)
                .after(setup::setup_rendered),
        );
    }
}

pub(crate) struct RenderedSceneRuntimePlugin;

impl Plugin for RenderedSceneRuntimePlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(PreUpdate, effects::clear_killed_enemies);
        app.add_systems(
            Update,
            crate::scene_instance_visuals::ensure_scene_instance_visuals_spawned,
        );
        app.add_systems(Update, scene_store::apply_pending_workspace_switch);
        app.add_systems(
            Update,
            (
                crate::motion::ensure_default_motion_algorithm_controllers,
                crate::motion::apply_motion_algorithms_on_controller_change
                    .after(crate::motion::ensure_default_motion_algorithm_controllers),
                crate::motion::apply_motion_algorithms_on_new_bindings
                    .after(crate::motion::apply_motion_algorithms_on_controller_change),
            )
                .after(crate::scene_instance_visuals::ensure_scene_instance_visuals_spawned)
                .before(crate::object::visuals::update_part_animations)
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(Update, crate::object_forms::ensure_object_forms_component);
        app.add_systems(
            Update,
            (
                crate::object_forms::tick_form_transform_animations,
                crate::object_forms::sync_form_badges
                    .after(crate::object_forms::tick_form_transform_animations),
                crate::object_forms::update_form_badges
                    .after(crate::object_forms::sync_form_badges),
            )
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(
            Update,
            crate::object::visuals::apply_pending_scene_overrides
                .after(crate::scene_instance_visuals::ensure_scene_instance_visuals_spawned),
        );
        app.add_systems(
            Update,
            (
                locomotion::ensure_animation_channels_active,
                locomotion::ensure_locomotion_clocks,
                locomotion::update_locomotion_clocks
                    .after(locomotion::ensure_locomotion_clocks)
                    .after(rts::execute_move_orders)
                    .after(enemies::move_enemies)
                    .after(physics::separate_enemies)
                    .after(physics::separate_player_from_enemies),
            )
                .before(crate::object::visuals::update_part_animations),
        );
        app.add_systems(
            Update,
            locomotion::update_animation_channels_active
                .after(locomotion::ensure_animation_channels_active)
                .after(locomotion::update_locomotion_clocks)
                .after(rts::execute_move_orders)
                .after(rts::update_fire_control)
                .after(combat::unit_attack_execute)
                .before(crate::object::visuals::update_part_animations)
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(Update, crate::object::visuals::update_part_animations);
        app.add_systems(
            PostUpdate,
            (
                scene_store::scene_autosave_detect_changes,
                scene_store::scene_save_requests.after(scene_store::scene_autosave_detect_changes),
                scene_store::scene_autosave_tick.after(scene_store::scene_save_requests),
                scene_store::apply_pending_realm_scene_switch
                    .after(scene_store::scene_autosave_tick),
            ),
        );
    }
}

pub(crate) struct RenderedUiPlugin;

impl Plugin for RenderedUiPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(
            PreUpdate,
            (
                crate::scene_authoring_ui::scene_ui_text_input,
                crate::scene_authoring_ui::scene_ui_clear_keyboard_state_when_captured
                    .after(crate::scene_authoring_ui::scene_ui_text_input),
                crate::workspace_scenes_ui::scenes_panel_text_input,
                crate::workspace_scenes_ui::scenes_panel_clear_keyboard_state_when_captured
                    .after(crate::workspace_scenes_ui::scenes_panel_text_input),
                crate::motion_ui::meta_speak_ui_text_input,
                crate::motion_ui::meta_speak_ui_clear_keyboard_state_when_captured
                    .after(crate::motion_ui::meta_speak_ui_text_input),
            )
                .after(bevy::input::InputSystems),
        );

        app.add_systems(
            Update,
            (
                crate::build::update_game_mode_toggle_button_label,
                crate::action_log_ui::update_action_log_ui.after(crate::rts::execute_move_orders),
                crate::workspace_ui::workspace_ui_update_visibility,
                crate::workspace_ui::workspace_toolbar_update_visibility
                    .after(crate::workspace_ui::workspace_ui_update_visibility),
                crate::workspace_ui::workspace_toolbar_sync_model_library_open
                    .after(crate::workspace_ui::workspace_toolbar_update_visibility),
                crate::workspace_ui::workspace_toolbar_update_toggle_button_styles
                    .after(crate::workspace_ui::workspace_toolbar_sync_model_library_open),
                crate::workspace_ui::workspace_toolbar_update_scene_builder_button_styles
                    .after(crate::workspace_ui::workspace_toolbar_update_toggle_button_styles),
                crate::workspace_ui::workspace_toolbar_update_scenes_panel_visibility.after(
                    crate::workspace_ui::workspace_toolbar_update_scene_builder_button_styles,
                ),
            ),
        );

        app.add_systems(
            Update,
            (
                crate::workspace_scenes_ui::scenes_panel_sync_active_realm
                    .after(crate::workspace_ui::workspace_toolbar_update_scenes_panel_visibility),
                crate::workspace_scenes_ui::scenes_panel_set_add_panel_visibility
                    .after(crate::workspace_scenes_ui::scenes_panel_sync_active_realm)
                    .after(crate::workspace_scenes_ui::scenes_panel_add_scene_button_actions)
                    .after(crate::workspace_scenes_ui::scenes_panel_add_panel_buttons),
                crate::workspace_scenes_ui::scenes_panel_rebuild_list_ui
                    .after(crate::workspace_scenes_ui::scenes_panel_sync_active_realm)
                    .after(crate::workspace_scenes_ui::scenes_panel_add_panel_buttons),
                crate::workspace_scenes_ui::scenes_panel_update_texts
                    .after(crate::workspace_scenes_ui::scenes_panel_set_add_panel_visibility),
                crate::workspace_scenes_ui::scenes_panel_update_styles
                    .after(crate::workspace_scenes_ui::scenes_panel_update_texts),
            ),
        );
        app.add_systems(
            Update,
            (
                crate::workspace_ui::workspace_toolbar_toggle_buttons,
                crate::workspace_ui::workspace_toolbar_scene_builder_button_interactions,
                crate::build::handle_game_mode_toggle_button,
                crate::action_log_ui::handle_action_log_toggle_button,
            )
                .run_if(console::console_closed)
                .run_if(crate::automation::local_input_enabled),
        );

        app.add_systems(
            Update,
            (
                crate::model_library_ui::model_library_update_visibility
                    .after(crate::workspace_ui::workspace_toolbar_sync_model_library_open),
                crate::model_library_ui::model_library_rebuild_list_ui
                    .after(crate::model_library_ui::model_library_update_visibility),
            ),
        );
        app.add_systems(
            Update,
            (
                crate::model_library_ui::model_library_gen3d_button_interactions
                    .run_if(crate::automation::local_input_enabled),
                crate::model_library_ui::model_library_item_button_interactions
                    .run_if(crate::automation::local_input_enabled),
                crate::model_library_ui::model_library_scroll_wheel
                    .after(crate::model_library_ui::model_library_item_button_interactions)
                    .run_if(crate::automation::local_input_enabled),
                crate::model_library_ui::model_library_scrollbar_drag
                    .after(crate::model_library_ui::model_library_scroll_wheel)
                    .run_if(crate::automation::local_input_enabled),
                crate::model_library_ui::model_library_drag_update
                    .after(crate::model_library_ui::model_library_item_button_interactions)
                    .run_if(crate::automation::local_input_enabled),
                crate::model_library_ui::model_library_draw_drag_preview_gizmos
                    .after(crate::model_library_ui::model_library_drag_update),
            )
                .run_if(console::console_closed)
                .run_if(crate::scene_authoring_ui::scene_ui_closed),
        );

        app.add_systems(
            Update,
            (
                crate::workspace_scenes_ui::scenes_panel_add_scene_button_actions
                    .run_if(crate::automation::local_input_enabled),
                crate::workspace_scenes_ui::scenes_panel_scene_select_button_actions
                    .after(crate::workspace_scenes_ui::scenes_panel_add_scene_button_actions)
                    .run_if(crate::automation::local_input_enabled),
                crate::workspace_scenes_ui::scenes_panel_add_panel_buttons
                    .after(crate::workspace_scenes_ui::scenes_panel_scene_select_button_actions)
                    .run_if(crate::automation::local_input_enabled),
                crate::workspace_scenes_ui::scenes_panel_name_field_focus
                    .after(crate::workspace_scenes_ui::scenes_panel_add_panel_buttons)
                    .run_if(crate::automation::local_input_enabled),
                crate::workspace_scenes_ui::scenes_panel_scroll_wheel
                    .after(crate::workspace_scenes_ui::scenes_panel_name_field_focus)
                    .run_if(crate::automation::local_input_enabled),
            )
                .run_if(console::console_closed)
                .run_if(in_state(BuildScene::Realm))
                .run_if(crate::scene_authoring_ui::scene_ui_closed),
        );

        app.add_systems(
            Update,
            (
                console::toggle_command_console,
                console::command_console_text_input.after(console::toggle_command_console),
                console::update_command_console_ui.after(console::command_console_text_input),
            )
                .run_if(in_state(BuildScene::Realm))
                .run_if(crate::scene_authoring_ui::scene_ui_closed)
                .run_if(crate::automation::local_input_enabled),
        );

        app.add_systems(
            Update,
            (
                crate::scene_authoring_ui::scene_ui_toggle_button,
                crate::scene_authoring_ui::scene_ui_close_button
                    .after(crate::scene_authoring_ui::scene_ui_toggle_button),
                crate::scene_authoring_ui::scene_ui_panel_visibility
                    .after(crate::scene_authoring_ui::scene_ui_close_button),
                crate::scene_authoring_ui::scene_ui_sync_active_scene
                    .after(crate::scene_authoring_ui::scene_ui_panel_visibility),
                crate::scene_authoring_ui::scene_ui_realm_dropdown_button
                    .after(crate::scene_authoring_ui::scene_ui_sync_active_scene),
                crate::scene_authoring_ui::scene_ui_rebuild_realm_list
                    .after(crate::scene_authoring_ui::scene_ui_realm_dropdown_button),
                crate::scene_authoring_ui::scene_ui_rebuild_scene_tabs
                    .after(crate::scene_authoring_ui::scene_ui_rebuild_realm_list),
                crate::scene_authoring_ui::scene_ui_realm_option_buttons
                    .after(crate::scene_authoring_ui::scene_ui_rebuild_scene_tabs),
                crate::scene_authoring_ui::scene_ui_scene_tab_buttons
                    .after(crate::scene_authoring_ui::scene_ui_realm_option_buttons),
                crate::scene_authoring_ui::scene_ui_update_realm_scene_button_styles
                    .after(crate::scene_authoring_ui::scene_ui_scene_tab_buttons),
                crate::scene_authoring_ui::scene_ui_text_field_focus,
                crate::scene_authoring_ui::scene_ui_action_buttons
                    .after(crate::scene_authoring_ui::scene_ui_text_field_focus),
                crate::scene_build_ai::scene_build_ai_poll
                    .after(crate::scene_authoring_ui::scene_ui_action_buttons),
                crate::scene_authoring_ui::scene_ui_update_texts
                    .after(crate::scene_build_ai::scene_build_ai_poll)
                    .after(crate::scene_authoring_ui::scene_ui_update_realm_scene_button_styles),
            )
                .run_if(console::console_closed)
                .run_if(in_state(BuildScene::Realm))
                .run_if(crate::automation::local_input_enabled),
        );
        app.add_systems(
            Update,
            (
                crate::gen3d::handle_gen3d_toggle_button,
                crate::gen3d::update_gen3d_toggle_button_label
                    .after(crate::gen3d::handle_gen3d_toggle_button),
            )
                .run_if(console::console_closed)
                .run_if(crate::scene_authoring_ui::scene_ui_closed)
                .run_if(crate::automation::local_input_enabled),
        );
    }
}

pub(crate) struct RenderedGen3dPlugin;

impl Plugin for RenderedGen3dPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(Startup, crate::gen3d::gen3d_load_tool_feedback_history);

        app.add_systems(OnEnter(BuildScene::Preview), crate::gen3d::enter_gen3d_mode);
        app.add_systems(OnExit(BuildScene::Preview), crate::gen3d::exit_gen3d_mode);

        app.add_systems(
            Update,
            (
                crate::gen3d::gen3d_handle_drag_and_drop
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_clear_images_button
                    .after(crate::gen3d::gen3d_handle_drag_and_drop)
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_prompt_box_focus.run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_side_panel_toggle_button
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_side_tab_buttons.run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_clear_prompt_button
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_preview_animation_dropdown_button
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_preview_animation_option_buttons
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_collision_toggle_button
                    .after(crate::gen3d::gen3d_prompt_box_focus)
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_generate_button
                    .after(crate::gen3d::gen3d_prompt_box_focus)
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_continue_button
                    .after(crate::gen3d::gen3d_prompt_box_focus)
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_save_button
                    .after(crate::gen3d::gen3d_poll_ai_job)
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_images_scroll_wheel
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_status_scroll_wheel
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_tool_feedback_scroll_wheel
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_prompt_scroll_wheel
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_preview_animation_dropdown_scroll_wheel
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_preview_orbit_controls
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_copy_tool_feedback_buttons
                    .run_if(crate::automation::local_input_enabled),
            )
                .run_if(in_state(BuildScene::Preview)),
        );
        app.add_systems(
            Update,
            (
                crate::gen3d::gen3d_preview_tick_selected_animation
                    .after(crate::gen3d::gen3d_apply_draft_to_preview)
                    .before(crate::object::visuals::update_part_animations),
                crate::gen3d::gen3d_update_collision_overlay
                    .after(crate::gen3d::gen3d_apply_draft_to_preview)
                    .after(crate::gen3d::gen3d_collision_toggle_button),
            )
                .run_if(in_state(BuildScene::Preview)),
        );
        app.add_systems(
            Update,
            crate::gen3d::gen3d_apply_pending_seed_from_prefab
                .run_if(in_state(BuildScene::Preview))
                .before(crate::gen3d::gen3d_poll_ai_job),
        );
        app.add_systems(
            Update,
            crate::gen3d::gen3d_poll_ai_job.after(crate::gen3d::gen3d_generate_button),
        );
        app.add_systems(
            Update,
            crate::gen3d::gen3d_apply_draft_to_preview
                .after(crate::gen3d::gen3d_poll_ai_job)
                .after(crate::gen3d::gen3d_collision_toggle_button),
        );
        app.add_systems(
            Update,
            crate::gen3d::gen3d_cleanup_preview_scene_when_idle
                .after(crate::gen3d::gen3d_apply_draft_to_preview)
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(
            Update,
            (
                crate::gen3d::gen3d_rebuild_images_list_ui
                    .after(crate::gen3d::gen3d_handle_drag_and_drop)
                    .after(crate::gen3d::gen3d_clear_images_button),
                crate::gen3d::gen3d_update_images_tip_visibility
                    .after(crate::gen3d::gen3d_handle_drag_and_drop)
                    .after(crate::gen3d::gen3d_clear_images_button),
                crate::gen3d::gen3d_thumbnail_button_open_viewer
                    .after(crate::gen3d::gen3d_rebuild_images_list_ui)
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_thumbnail_button_style_on_interaction
                    .after(crate::gen3d::gen3d_rebuild_images_list_ui)
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_update_thumbnail_tooltip
                    .after(crate::gen3d::gen3d_thumbnail_button_style_on_interaction)
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_image_viewer_keyboard_navigation
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_prompt_text_input
                    .after(crate::gen3d::gen3d_prompt_box_focus)
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_image_viewer_click_to_close
                    .after(crate::gen3d::gen3d_thumbnail_button_open_viewer)
                    .run_if(crate::automation::local_input_enabled),
                crate::gen3d::gen3d_update_image_viewer_ui
                    .after(crate::gen3d::gen3d_image_viewer_keyboard_navigation)
                    .after(crate::gen3d::gen3d_image_viewer_click_to_close),
                crate::gen3d::gen3d_thumbnail_button_style_on_selection
                    .after(crate::gen3d::gen3d_image_viewer_keyboard_navigation)
                    .after(crate::gen3d::gen3d_image_viewer_click_to_close),
                crate::gen3d::gen3d_update_ui_text
                    .after(crate::gen3d::gen3d_prompt_text_input)
                    .after(crate::gen3d::gen3d_clear_prompt_button)
                    .after(crate::gen3d::gen3d_preview_animation_dropdown_button)
                    .after(crate::gen3d::gen3d_preview_animation_option_buttons)
                    .after(crate::gen3d::gen3d_collision_toggle_button)
                    .after(crate::gen3d::gen3d_poll_ai_job),
                crate::gen3d::gen3d_rebuild_preview_animation_dropdown_options_ui
                    .after(crate::gen3d::gen3d_apply_draft_to_preview),
                crate::gen3d::gen3d_update_preview_animation_dropdown_ui
                    .after(crate::gen3d::gen3d_update_ui_text),
                crate::gen3d::gen3d_update_side_panel_ui
                    .after(crate::gen3d::gen3d_update_ui_text)
                    .after(crate::gen3d::gen3d_side_panel_toggle_button),
                crate::gen3d::gen3d_update_side_tab_ui.after(crate::gen3d::gen3d_update_ui_text),
                crate::gen3d::gen3d_update_tool_feedback_text
                    .after(crate::gen3d::gen3d_update_side_tab_ui),
            )
                .run_if(in_state(BuildScene::Preview)),
        );
        app.add_systems(
            PostUpdate,
            (
                crate::gen3d::gen3d_update_images_scrollbar_ui,
                crate::gen3d::gen3d_update_prompt_scrollbar_ui,
                crate::gen3d::gen3d_update_status_scrollbar_ui,
                crate::gen3d::gen3d_update_tool_feedback_scrollbar_ui,
            )
                .in_set(UiSystems::Content)
                .run_if(in_state(BuildScene::Preview)),
        );
        app.add_systems(
            PostUpdate,
            (
                crate::model_library_ui::model_library_update_scrollbar_ui,
                crate::motion_ui::motion_algorithm_ui_update_scrollbar_ui,
            )
                .in_set(UiSystems::Content)
                .run_if(in_state(BuildScene::Realm)),
        );
    }
}

pub(crate) struct RenderedGameplayPlugin;

fn auto_spawn_enemies_enabled(auto_spawn: Res<AutoSpawnEnemies>) -> bool {
    auto_spawn.0
}

impl Plugin for RenderedGameplayPlugin {
    fn build(&self, app: &mut App) {
        app.add_systems(
            Update,
            (
                unit_health::ensure_health_for_commandables,
                unit_health::ensure_laser_damage_accum_for_units
                    .after(unit_health::ensure_health_for_commandables),
                unit_health::update_die_motions,
            )
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(
            Update,
            player::update_edge_scroll_cursor_indicator
                .after(console::update_command_console_ui)
                .run_if(in_state(BuildScene::Realm))
                .run_if(crate::automation::local_input_enabled),
        );
        app.add_systems(
            Update,
            (common::restart_game, build::toggle_game_mode)
                .run_if(console::console_closed)
                .run_if(crate::scene_authoring_ui::scene_ui_closed)
                .run_if(in_state(BuildScene::Realm))
                .run_if(crate::automation::local_input_enabled),
        );
        app.add_systems(
            Update,
            (
                crate::world_drag::world_drag_start
                    .before(rts::selection_input)
                    .run_if(crate::automation::local_input_enabled),
                crate::world_drag::world_drag_update
                    .after(crate::world_drag::world_drag_start)
                    .before(rts::selection_input)
                    .run_if(crate::automation::local_input_enabled),
            )
                .run_if(in_state(GameMode::Build))
                .run_if(console::console_closed)
                .run_if(crate::scene_authoring_ui::scene_ui_closed)
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(
            Update,
            (
                rts::selection_input.run_if(crate::automation::local_input_enabled),
                rts::draw_box_selection_preview_gizmos.after(rts::selection_input),
                rts::draw_hover_selection_circle_gizmos.after(rts::selection_input),
                crate::object_forms::object_forms_copy_mode_start_cancel
                    .after(rts::selection_input),
                crate::object_forms::object_forms_copy_mode_update_cursor
                    .after(crate::object_forms::object_forms_copy_mode_start_cancel)
                    .after(player::update_edge_scroll_cursor_indicator),
                crate::object_forms::object_forms_copy_mode_confirm_on_release
                    .after(crate::object_forms::object_forms_copy_mode_update_cursor),
                crate::object_forms::object_forms_tab_switch_selected.after(rts::selection_input),
                rts::toggle_slow_move_mode
                    .after(rts::selection_input)
                    .before(rts::keyboard_move_input)
                    .run_if(crate::automation::local_input_enabled),
                rts::update_selection_box_ui.after(rts::selection_input),
                rts::draw_selected_player_gizmos.after(rts::selection_input),
                rts::unit_animation_hotkeys
                    .after(rts::selection_input)
                    .before(rts::update_fire_control)
                    .run_if(crate::automation::local_input_enabled),
                rts::update_fire_control
                    .after(rts::selection_input)
                    .run_if(crate::automation::local_input_enabled),
                rts::move_command_input
                    .after(rts::selection_input)
                    .before(build::build_remove_object)
                    .run_if(crate::automation::local_input_enabled),
                rts::keyboard_move_input
                    .after(rts::move_command_input)
                    .before(rts::execute_move_orders)
                    .run_if(crate::automation::local_input_enabled),
                rts::execute_move_orders.after(rts::keyboard_move_input),
                rts::update_unit_aim_yaw_delta
                    .after(rts::execute_move_orders)
                    .after(rts::update_fire_control)
                    .before(crate::object::visuals::update_part_animations),
                combat::ensure_attack_cooldowns.after(rts::selection_input),
                combat::tick_attack_cooldowns.after(combat::ensure_attack_cooldowns),
                combat::unit_attack_execute
                    .after(rts::update_unit_aim_yaw_delta)
                    .after(combat::tick_attack_cooldowns),
                rts::clear_forced_animation_channel_after_one_shot
                    .after(combat::unit_attack_execute)
                    .after(combat::brain_attack_execute),
            )
                .run_if(console::console_closed)
                .run_if(crate::scene_authoring_ui::scene_ui_closed)
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(
            Update,
            rts::update_brain_attack_aim_yaw_delta
                .after(rts::update_unit_aim_yaw_delta)
                .before(crate::object::visuals::update_part_animations)
                .run_if(in_state(GameMode::Play))
                .run_if(console::console_closed)
                .run_if(crate::scene_authoring_ui::scene_ui_closed)
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(
            Update,
            combat::brain_attack_execute
                .after(rts::execute_move_orders)
                .after(combat::tick_attack_cooldowns)
                .run_if(in_state(GameMode::Play))
                .run_if(console::console_closed)
                .run_if(crate::scene_authoring_ui::scene_ui_closed)
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(
            Update,
            (
                crate::motion_ui::motion_algorithm_ui_keyboard
                    .run_if(crate::automation::local_input_enabled),
                crate::motion_ui::motion_algorithm_ui_update
                    .after(crate::motion_ui::motion_algorithm_ui_keyboard),
                crate::motion_ui::motion_algorithm_ui_button_clicks
                    .after(crate::motion_ui::motion_algorithm_ui_update)
                    .run_if(crate::automation::local_input_enabled),
                crate::motion_ui::meta_brain_ui_button_clicks
                    .after(crate::motion_ui::motion_algorithm_ui_update)
                    .run_if(crate::automation::local_input_enabled),
                crate::motion_ui::meta_gen3d_ui_button_clicks
                    .after(crate::motion_ui::motion_algorithm_ui_update)
                    .run_if(crate::automation::local_input_enabled),
                crate::motion_ui::meta_speak_ui_content_field_focus
                    .after(crate::motion_ui::motion_algorithm_ui_update)
                    .run_if(crate::automation::local_input_enabled),
                crate::motion_ui::meta_speak_ui_button_clicks
                    .after(crate::motion_ui::meta_speak_ui_content_field_focus)
                    .run_if(crate::automation::local_input_enabled),
                crate::motion_ui::motion_algorithm_ui_button_styles
                    .after(crate::motion_ui::motion_algorithm_ui_button_clicks),
                crate::motion_ui::meta_brain_ui_button_styles
                    .after(crate::motion_ui::meta_brain_ui_button_clicks),
                crate::motion_ui::meta_gen3d_ui_button_styles
                    .after(crate::motion_ui::meta_gen3d_ui_button_clicks),
                crate::motion_ui::meta_speak_ui_button_styles
                    .after(crate::motion_ui::meta_speak_ui_button_clicks),
                crate::motion_ui::motion_algorithm_ui_scroll_wheel
                    .after(crate::motion_ui::motion_algorithm_ui_button_styles)
                    .after(crate::motion_ui::meta_brain_ui_button_styles)
                    .after(crate::motion_ui::meta_gen3d_ui_button_styles)
                    .after(crate::motion_ui::meta_speak_ui_button_styles)
                    .run_if(crate::automation::local_input_enabled),
                crate::motion_ui::motion_algorithm_ui_scrollbar_drag
                    .after(crate::motion_ui::motion_algorithm_ui_scroll_wheel)
                    .run_if(crate::automation::local_input_enabled),
            )
                .after(rts::selection_input)
                .run_if(console::console_closed)
                .run_if(crate::scene_authoring_ui::scene_ui_closed)
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(
            Update,
            (
                crate::ui::update_window_title,
                crate::ui::update_fps_counter,
                crate::ui::update_minimap
                    .after(player::camera_follow)
                    .after(rts::execute_move_orders)
                    .after(physics::separate_player_from_enemies)
                    .after(physics::separate_enemies)
                    .after(enemies::move_enemies),
            ),
        );
        app.add_systems(
            PostUpdate,
            (
                crate::ui::spawn_health_change_popups.in_set(UiSystems::Content),
                crate::ui::apply_model_speech_bubble_commands
                    .after(crate::ui::spawn_health_change_popups)
                    .in_set(UiSystems::Content),
                crate::ui::update_model_speech_bubbles
                    .after(crate::ui::apply_model_speech_bubble_commands)
                    .in_set(UiSystems::Content),
                crate::ui::update_health_change_popups
                    .after(crate::ui::update_model_speech_bubbles)
                    .in_set(UiSystems::Content),
            ),
        );
        app.add_systems(
            Update,
            common::tick_cooldowns
                .run_if(console::console_closed)
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(
            Update,
            physics::separate_commandables
                .after(rts::execute_move_orders)
                .after(physics::separate_enemies)
                .run_if(console::console_closed)
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(
            Update,
            physics::separate_player_from_enemies
                .after(physics::separate_commandables)
                .after(rts::execute_move_orders)
                .after(physics::separate_enemies)
                .run_if(console::console_closed)
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(
            Update,
            player::animate_player_model
                .after(physics::separate_player_from_enemies)
                .run_if(console::console_closed)
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(
            Update,
            player::camera_zoom_input
                .before(player::camera_follow)
                .run_if(console::console_closed)
                .run_if(crate::scene_authoring_ui::scene_ui_closed)
                .run_if(in_state(BuildScene::Realm))
                .run_if(crate::automation::local_input_enabled),
        );
        app.add_systems(
            Update,
            (
                player::camera_keyboard_rotate
                    .after(player::camera_zoom_input)
                    .run_if(crate::automation::local_input_enabled),
                player::camera_edge_pan
                    .after(player::camera_keyboard_rotate)
                    .run_if(crate::automation::local_input_enabled),
                player::camera_keyboard_pan
                    .after(player::camera_edge_pan)
                    .run_if(crate::automation::local_input_enabled),
                player::camera_follow_selection.after(player::camera_keyboard_pan),
            )
                .before(player::camera_follow)
                .run_if(console::console_closed)
                .run_if(crate::scene_authoring_ui::scene_ui_closed)
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(
            Update,
            player::camera_follow
                .before(rts::selection_input)
                .run_if(console::console_closed)
                .run_if(in_state(BuildScene::Realm)),
        );
        app.add_systems(
            Update,
            player::aim_player
                .after(player::camera_follow)
                .run_if(console::console_closed)
                .run_if(crate::scene_authoring_ui::scene_ui_closed)
                .run_if(in_state(BuildScene::Realm))
                .run_if(crate::automation::local_input_enabled),
        );
        app.add_systems(
            OnEnter(GameMode::Build),
            (
                build::enter_build_mode,
                unit_health::recover_health_on_enter_build_mode.after(build::enter_build_mode),
            ),
        );
        app.add_systems(
            OnEnter(GameMode::Play),
            (
                build::enter_play_mode,
                rts::ensure_default_selection_on_enter_play.after(build::enter_play_mode),
            ),
        );
        app.add_systems(
            OnEnter(GameMode::Play),
            scene_store::request_scene_save_on_enter_play.after(build::enter_play_mode),
        );

        app.add_systems(
            Update,
            (
                build::build_cancel_preview_and_clear_selection,
                build::build_select_object.after(build::build_cancel_preview_and_clear_selection),
                build::build_toggle_fence_axis.after(build::build_select_object),
                build::build_update_preview
                    .after(player::aim_player)
                    .after(build::build_select_object)
                    .after(build::build_toggle_fence_axis)
                    .after(build::build_cancel_preview_and_clear_selection),
                build::build_draw_preview_gizmos.after(build::build_update_preview),
                build::build_place_object
                    .after(player::aim_player)
                    .after(build::build_select_object)
                    .after(build::build_toggle_fence_axis)
                    .after(build::build_cancel_preview_and_clear_selection),
                build::build_remove_object
                    .after(player::aim_player)
                    .after(build::build_cancel_preview_and_clear_selection),
                build::build_edit_selected_objects
                    .after(rts::selection_input)
                    .after(build::build_cancel_preview_and_clear_selection),
                rts::build_unit_hotkeys.after(build::build_edit_selected_objects),
                build::build_remove_selected_objects.after(build::build_edit_selected_objects),
                build::build_draw_selection_gizmos.after(build::build_remove_selected_objects),
            )
                .run_if(in_state(GameMode::Build))
                .run_if(in_state(BuildScene::Realm))
                .run_if(console::console_closed)
                .run_if(crate::scene_authoring_ui::scene_ui_closed)
                .run_if(crate::automation::local_input_enabled),
        );

        app.add_systems(
            Update,
            (
                combat::switch_player_weapon.run_if(crate::automation::local_input_enabled),
                combat::player_fire
                    .after(rts::update_fire_control)
                    .after(combat::switch_player_weapon),
                combat::update_lasers
                    .after(rts::update_fire_control)
                    .after(combat::player_fire),
                combat::laser_kill_enemies.after(enemies::move_enemies),
            )
                .run_if(in_state(GameMode::Play).or(in_state(GameMode::Build)))
                .run_if(in_state(BuildScene::Realm))
                .run_if(console::console_closed),
        );
        app.add_systems(
            Update,
            player::update_player_gun_visuals
                .after(common::restart_game)
                .after(combat::switch_player_weapon)
                .after(combat::player_fire)
                .run_if(console::console_closed),
        );
        app.add_systems(
            Update,
            (
                combat::move_bullets,
                combat::bullet_object_collisions.after(combat::move_bullets),
                combat::despawn_expired_bullets.after(combat::move_bullets),
            )
                .run_if(in_state(GameMode::Play).or(in_state(GameMode::Build)))
                .run_if(in_state(BuildScene::Realm))
                .run_if(console::console_closed),
        );
        app.add_systems(
            Update,
            (
                enemies::enemy_shooting.after(enemies::move_enemies),
                enemies::gundam_shooting.after(enemies::move_enemies),
                enemies::move_enemy_projectiles
                    .after(enemies::enemy_shooting)
                    .after(enemies::gundam_shooting),
                effects::animate_energy_ball_visuals.after(enemies::move_enemy_projectiles),
                enemies::enemy_projectile_object_collisions
                    .after(effects::animate_energy_ball_visuals),
                enemies::enemy_projectile_player_collisions
                    .after(enemies::enemy_projectile_object_collisions),
            )
                .run_if(in_state(GameMode::Play))
                .run_if(console::console_closed),
        );
        app.add_systems(
            Update,
            (
                enemies::spawn_enemies
                    .before(enemies::move_enemies)
                    .run_if(auto_spawn_enemies_enabled),
                enemies::move_enemies,
                enemies::tick_dog_pounce_cooldowns.after(enemies::move_enemies),
                enemies::dog_try_start_pounce.after(enemies::tick_dog_pounce_cooldowns),
                enemies::update_dog_pounces.after(enemies::dog_try_start_pounce),
                physics::separate_enemies.after(enemies::update_dog_pounces),
                enemies::animate_enemy_models.after(physics::separate_enemies),
            )
                .run_if(in_state(GameMode::Play))
                .run_if(console::console_closed),
        );
        app.add_systems(
            Update,
            enemies::dog_bite_attack
                .after(physics::separate_player_from_enemies)
                .run_if(in_state(GameMode::Play))
                .run_if(console::console_closed),
        );
        app.add_systems(
            Update,
            (
                combat::bullet_enemy_collisions.after(combat::move_bullets),
                effects::spawn_explosions
                    .after(combat::bullet_enemy_collisions)
                    .after(combat::laser_kill_enemies),
            )
                .run_if(in_state(GameMode::Play))
                .run_if(console::console_closed),
        );
        app.add_systems(
            Update,
            effects::update_explosion_particles.run_if(console::console_closed),
        );
    }
}
