use bevy::prelude::*;

#[derive(Resource)]
pub(crate) struct SceneAssets {
    pub(crate) unit_cube_mesh: Handle<Mesh>,
    pub(crate) unit_cylinder_mesh: Handle<Mesh>,
    pub(crate) unit_cone_mesh: Handle<Mesh>,
    pub(crate) unit_sphere_mesh: Handle<Mesh>,
    pub(crate) unit_plane_mesh: Handle<Mesh>,
    pub(crate) unit_capsule_mesh: Handle<Mesh>,
    pub(crate) unit_conical_frustum_mesh: Handle<Mesh>,
    pub(crate) unit_torus_mesh: Handle<Mesh>,
    pub(crate) unit_triangle_mesh: Handle<Mesh>,
    pub(crate) unit_tetrahedron_mesh: Handle<Mesh>,
    pub(crate) dog_material: Handle<StandardMaterial>,
    pub(crate) human_material: Handle<StandardMaterial>,
    pub(crate) gundam_material: Handle<StandardMaterial>,
    pub(crate) enemy_gun_material: Handle<StandardMaterial>,
    pub(crate) enemy_bullet_mesh: Handle<Mesh>,
    pub(crate) enemy_bullet_material: Handle<StandardMaterial>,
    pub(crate) enemy_bullet_spot_mesh: Handle<Mesh>,
    pub(crate) enemy_bullet_spot_material: Handle<StandardMaterial>,
    pub(crate) gundam_energy_ball_mesh: Handle<Mesh>,
    pub(crate) gundam_energy_ball_material: Handle<StandardMaterial>,
    pub(crate) gundam_energy_arc_material: Handle<StandardMaterial>,
    pub(crate) gundam_energy_impact_material: Handle<StandardMaterial>,
    pub(crate) explosion_material: Handle<StandardMaterial>,
    pub(crate) blood_material: Handle<StandardMaterial>,
    pub(crate) bullet_mesh: Handle<Mesh>,
    pub(crate) bullet_material: Handle<StandardMaterial>,
    pub(crate) shotgun_pellet_mesh: Handle<Mesh>,
    pub(crate) shotgun_pellet_material: Handle<StandardMaterial>,
    pub(crate) laser_mesh: Handle<Mesh>,
    pub(crate) laser_material: Handle<StandardMaterial>,
    pub(crate) build_block_materials: [Handle<StandardMaterial>; 3],
    pub(crate) fence_stake_material: Handle<StandardMaterial>,
    pub(crate) fence_stick_material: Handle<StandardMaterial>,
    pub(crate) tree_trunk_mesh: Handle<Mesh>,
    pub(crate) tree_cone_mesh: Handle<Mesh>,
    pub(crate) tree_trunk_materials: [Handle<StandardMaterial>; 3],
    pub(crate) tree_main_materials: [Handle<StandardMaterial>; 3],
    pub(crate) tree_crown_materials: [Handle<StandardMaterial>; 3],
    pub(crate) move_target_mesh: Handle<Mesh>,
    pub(crate) move_target_material: Handle<StandardMaterial>,
}
