mod action_log;
mod action_log_ui;
mod ai_limiter;
mod app;
mod app_plugins;
mod assets;
mod automation;
mod build;
mod clipboard;
mod combat;
mod common;
mod config;
mod console;
mod constants;
mod cursor_pick;
mod effects;
mod enemies;
mod gen3d;
mod geometry;
mod headless;
pub mod intelligence;
mod locomotion;
pub mod meta_speak;
mod model_library_ui;
mod model_tool;
mod models;
mod monitor_mode;
mod motion_ui;
mod navigation;
mod object;
mod object_forms;
mod openai_shared;
mod orbit_capture;
mod paths;
mod physics;
mod platform;
mod player;
mod prefab_descriptors;
mod realm;
mod realm_prefab_packages;
mod realm_prefabs;
mod rich_text;
mod rts;
mod scene_authoring_ui;
mod scene_build_ai;
mod scene_instance_visuals;
mod scene_prefabs;
mod scene_runs;
mod scene_sources;
mod scene_sources_patch;
mod scene_sources_runtime;
mod scene_store;
mod scene_validation;
mod selection_circle;
mod setup;
mod system_proxy;
mod threaded_result;
mod types;
mod ui;
mod unit_health;
mod workspace_scenes_ui;
mod workspace_ui;
mod world_drag;

pub fn run() {
    app::run();
}
